### ISSUE TITLE
would be nice to have an opam package for ocamlbrowser

### ISSUE THREAD

**Issue by UnixJunkie** [garrigue/labltk#3]
Even if the package is only virtual and only install labltk, that would be nice.
Cf. this also: https://github.com/ocaml/opam-repository/issues/7061

**Comment by UnixJunkie** [comment]
related to https://github.com/ocaml/opam-repository/pull/13328#issuecomment-462098212

**Comment by UnixJunkie** [comment]
if you put browser in its own source code repository (and tag/release it), then it is just a matter of adding an opam file, right?

**Comment by garrigue** [comment]
I created an opam package at last. There is only one source archive, but ocamlbrowser can be installed separately.

**Comment by UnixJunkie** [comment]
Thanks a lot!
