### ISSUE TITLE
Weird build error on 4.05

### ISSUE THREAD

**Issue by gasche** [garrigue/labltk#4]
opam-builder fails to build labltk on 4.05 with the following error message (see the [full log](http://opam.ocamlpro.com/builder/html/labltk/labltk.8.06.2/828b396e6771d0021d365403f9b23878)):

> Error: Error on dynamically loaded library: ../support/dlllabltk.so: ../support/dlllabltk.so: undefined symbol: convert_flag_list

Do you know whether this is a labltk issue? (It could be a more obscure packaging or opam-builder-environment issue, although labltk.8.06.2 builds correctly on 4.04). Can you build under 4.05 on your own machine?

**Comment by olafhering** [comment]
This happens because BYTECC/NATIVECC defines CAML_NAME_SPACE, which hides the wrappers in /usr/lib64/ocaml/caml/compatibility.h

**Comment by glondu** [comment]
This is fixed in the Debian package:

  https://anonscm.debian.org/cgit/pkg-ocaml-maint/packages/labltk.git/tree/debian/patches

Patch 0001 already exists in the git repository; patches 0002 through 0004 are needed to compile labltk with ocaml 4.05 (patch 0003 partly reverts 0001).

**Comment by garrigue** [comment]
@glondu , thanks for the patches.
I merged them and release labltk-8.06.3.
The opam package is on its way.
