### ISSUE TITLE
Cannot install via opam on Ubuntu

### ISSUE THREAD

**Issue by hanjiexi** [garrigue/labltk#5]
Hello,

I am trying to install labltk 8.06.4 for OCaml 4.06.0 via Opam on Ubuntu 17.10. After running `opam install labltk`, I get this error:
```bash
### stderr ###
# cltkCaml.c:19:10: fatal error: tcl.h: No such file or directory
#  #include <tcl.h>
#           ^~~~~~~
# compilation terminated.
# make[1]: *** [cltkCaml.o] Error 1
# make: *** [all] Error 2



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  ∗  install labltk 8.06.4
No changes have been performed

=-=- labltk.8.06.4 troubleshooting =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
=> This package requires Tcl/Tk with its development packages installed on your
   system
```
However, the file in question is installed on the system:
```bash
$ ls /usr/include/tcl
tclDecls.h    tclOO.h         tclTomMathDecls.h  tk.h
tcl.h         tclPlatDecls.h  tclTomMath.h       tkPlatDecls.h
tclOODecls.h  tcl-private     tkDecls.h          tk-private
```
My guess would be that it's not recursively searching the subdirectories of `/usr/include`. But I don't think that can be an opam issue; I was able to install lablgtk just fine and its libraries are also stored in a subdirectory of `/usr/include`.

Note that labltk does install okay via the system's package manager, but the system's libraries are somewhat outdated so I prefer to have everything installed via opam.

**Comment by garrigue** [comment]
If you look at `configure`, it does not recurse inside `/usr/include`, but rather looks in a number of standard locations for `tcl.h`, and `/usr/include/tcl` is not among those, and nobody has ever reported this as missing.
The fix is easy, but it will have to wait for a while for my going back home :-)
Also, `lablgtk` relies on `pkgconfig` to find the right directory, so this is a completely different approach.

**Comment by hanjiexi** [comment]
Thanks for your response. Would the fix be as simple as adding:
```bash
 "-I/usr/include/tcl" \
```
at, say, line 174? If so, I can issue a pull request for this change.

**Comment by garrigue** [comment]
That's correct, but merging this pull request would not be sufficient to fix the opam package...

**Comment by hanjiexi** [comment]
I'm closing this as the issue is not present in Ubuntu 18.04, the current supported release.
